//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipFood.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFoodyEntities : DbContext
    {
        public dbFoodyEntities()
            : base("name=dbFoodyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAdmin> tbAdmins { get; set; }
        public virtual DbSet<tbChiTietDonHang> tbChiTietDonHangs { get; set; }
        public virtual DbSet<tbDanhGia> tbDanhGias { get; set; }
        public virtual DbSet<tbDanhMuc> tbDanhMucs { get; set; }
        public virtual DbSet<tbDonHang> tbDonHangs { get; set; }
        public virtual DbSet<tbKhachHang> tbKhachHangs { get; set; }
        public virtual DbSet<tbKhuyenMai> tbKhuyenMais { get; set; }
        public virtual DbSet<tbLoaiHinhThanhToan> tbLoaiHinhThanhToans { get; set; }
        public virtual DbSet<tbMonAn> tbMonAns { get; set; }
        public virtual DbSet<tbMonAnKhuyenMai> tbMonAnKhuyenMais { get; set; }
        public virtual DbSet<tbQuanAn> tbQuanAns { get; set; }
        public virtual DbSet<tbShipper> tbShippers { get; set; }
        public virtual DbSet<tbThongTinDatHang> tbThongTinDatHangs { get; set; }
        public virtual DbSet<tbTinNhan> tbTinNhans { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
    }
}
