//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbChiTietDonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbChiTietDonHang()
        {
            this.tbDanhGias = new HashSet<tbDanhGia>();
        }
    
        public int mactdh { get; set; }
        public Nullable<int> madh { get; set; }
        public Nullable<int> mamon { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> dongia { get; set; }
    
        public virtual tbMonAn tbMonAn { get; set; }
        public virtual tbDonHang tbDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDanhGia> tbDanhGias { get; set; }
    }
}
