//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDonHang()
        {
            this.tbChiTietDonHangs = new HashSet<tbChiTietDonHang>();
            this.tbTinNhans = new HashSet<tbTinNhan>();
        }
    
        public int madh { get; set; }
        public Nullable<int> maquan { get; set; }
        public Nullable<int> mattdh { get; set; }
        public Nullable<System.DateTime> ngaydathang { get; set; }
        public string trangthai { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public Nullable<int> hinhthucthanhtoan { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> makhuyenmai { get; set; }
        public Nullable<decimal> phiship { get; set; }
        public Nullable<decimal> phidichvu { get; set; }
        public Nullable<System.DateTime> ngaygiaohang { get; set; }
        public Nullable<System.DateTime> ngaythanhtoan { get; set; }
        public Nullable<int> mashipper { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbChiTietDonHang> tbChiTietDonHangs { get; set; }
        public virtual tbLoaiHinhThanhToan tbLoaiHinhThanhToan { get; set; }
        public virtual tbKhuyenMai tbKhuyenMai { get; set; }
        public virtual tbQuanAn tbQuanAn { get; set; }
        public virtual tbShipper tbShipper { get; set; }
        public virtual tbThongTinDatHang tbThongTinDatHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTinNhan> tbTinNhans { get; set; }
    }
}
