//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbKhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbKhuyenMai()
        {
            this.tbDonHangs = new HashSet<tbDonHang>();
            this.tbMonAnKhuyenMais = new HashSet<tbMonAnKhuyenMai>();
        }
    
        public int makm { get; set; }
        public string tenkm { get; set; }
        public string mota { get; set; }
        public string loaikm { get; set; }
        public Nullable<int> phantramgiam { get; set; }
        public string dieukien { get; set; }
        public Nullable<System.DateTime> ngaybatdau { get; set; }
        public Nullable<System.DateTime> ngayketthuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDonHang> tbDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMonAnKhuyenMai> tbMonAnKhuyenMais { get; set; }
    }
}
