//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMonAn()
        {
            this.tbChiTietDonHangs = new HashSet<tbChiTietDonHang>();
            this.tbMonAnKhuyenMais = new HashSet<tbMonAnKhuyenMai>();
        }
    
        public int mamon { get; set; }
        public string tenmon { get; set; }
        public string mota { get; set; }
        public Nullable<decimal> giatien { get; set; }
        public string hinhanh { get; set; }
        public Nullable<int> maquanan { get; set; }
        public Nullable<int> madanhmuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbChiTietDonHang> tbChiTietDonHangs { get; set; }
        public virtual tbDanhMuc tbDanhMuc { get; set; }
        public virtual tbQuanAn tbQuanAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMonAnKhuyenMai> tbMonAnKhuyenMais { get; set; }
    }
}
