//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMonAnKhuyenMai
    {
        public int id { get; set; }
        public Nullable<int> makm { get; set; }
        public Nullable<int> mamon { get; set; }
        public Nullable<int> soluong { get; set; }
        public string trangthai { get; set; }
        public int phantramgiam { get; set; }
    
        public virtual tbKhuyenMai tbKhuyenMai { get; set; }
        public virtual tbMonAn tbMonAn { get; set; }
    }
}
