//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbQuanAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbQuanAn()
        {
            this.tbDonHangs = new HashSet<tbDonHang>();
            this.tbMonAns = new HashSet<tbMonAn>();
        }
    
        public int userid { get; set; }
        public string tenquanan { get; set; }
        public string diachi { get; set; }
        public System.Data.Entity.Spatial.DbGeography toado { get; set; }
        public Nullable<int> soluotdanhgia { get; set; }
        public Nullable<decimal> diemdanhgia { get; set; }
        public string trangthai { get; set; }
        public string hinhanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDonHang> tbDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMonAn> tbMonAns { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
